-- Deploy cccs_service_area:001 to pg

BEGIN;

	CREATE EXTENSION IF NOT EXISTS postgis;

	CREATE SCHEMA cccs;

	CREATE TABLE cccs.service_area
	(
		id INT GENERATED BY DEFAULT AS IDENTITY,
		acronym TEXT NOT NULL,
		name TEXT NOT NULL,
		official_desc TEXT NOT NULL,
		way GEOMETRY (MULTIPOLYGON, 3857),
		CONSTRAINT PK_cccs_service_area_id PRIMARY KEY (id),
		CONSTRAINT UQ_cccs_service_area_acronym UNIQUE (acronym),
		CONSTRAINT UQ_cccs_service_area_name UNIQUE (name)
	);

	CREATE INDEX gix_cccs_service_area ON cccs.service_area
		USING GIST (way);

	COMMENT ON TABLE cccs.service_area IS 'Service areas for CCCS schools as defined in SP 9-20b.  Last updated 2001, Retreived 12/8/2019 from https://www.cccs.edu/policies-and-procedures/system-presidents-procedures/25687-2/

	Boundaries created one row at a time, leveraging U.S. Census Bureau data for counties and school districts.  Manual editing done via QGIS using OpenStreetMap data for referencing important locations for boundaries.';
	COMMENT ON COLUMN cccs.service_area.official_desc IS 'Text from CCCS'' SP 9-20b document.';



COMMIT;
